language: node_js
node_js:
  - "stable"
    # safelist
branches:
  only:
  - develop
env:
  global:
  - NODE_ENV=test

cache:
  directories:
    - "node_modules"
    - "test"
install:
  - npm install
services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE teamwork;' -U postgres
  - psql -U postgres -d teamwork -a -f init.sql
script:
  - npm test
  - npm run coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
