language: node_js
node_js:
  - "10.16.0"

before_install:
  - nvm install

install:
   - travis_wait npm install

cache:
  directories:
    - "node_modules"
    - "test"

    # safelist
branches:
  only:
  - develop
env:
  global:
  - NODE_ENV=test

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE teamwork;' -U postgres
  - psql -U postgres -d teamwork -a -f init.sql
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test
  
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - npm run coverage
