language: node_js
node_js:
  - "stable"
    # safelist
branches:
  only:
  - develop

cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test
  - DB_USER = charles
  - DB_PASSWORD = null
  - DB_PORT = 5432
  - DB_DATABASE = teamwork_test

before_script:
  - psql -c 'create database teamwork_test;' -U postgres
  - psql -c "CREATE USER charles WITH PASSWORD null;" -U postgres
script:
  - npm test
after_success:
  - npm run coverage
