language: node_js
node_js:
  - "stable"
install:
  - npm install

cache:
  directories:
    - "node_modules"
    - "test"

    # safelist
branches:
  only:
  - develop
env:
  global:
  - NODE_ENV=test

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE teamwork;' -U postgres
  - psql -U postgres -d teamwork -a -f init.sql
script:
  - npm test

after_success:
  - npm run coverage
